Database Source: https://www.w3schools.com/sql/trysql.asp?filename=trysql_select_all&comments=1

Exercises: 

** BASIC SQL QUERIES ** 
	
	1.Retrieve all columns from the "customers" table.
	
		SELECT  *
		FROM customers;
		
	2.Select only the "CustomerName" and "Country" columns from the "customers" table.
		
		SELECT CustomerName, Country
		FROM customers;
		
	3.Retrieve unique countries from the "customers" table.
		
		SELECT DISTINCT(country) 
		FROM customers;
		
	4.Display the first 5 rows from the "categories" table.
		
		SELECT * 
		FROM categories
		LIMIT 5;
		
	5.Count the number of rows in the "employees" table.
		
		SELECT COUNT(*) 
		FROM employees;
	
	6.Find the average price of products from the "products" table.
		
		SELECT AVG(price)
		FROM products;
		
	7.List all the distinct categories from the "categories" table.
		
		SELECT DISTINCT(CategoryName)
		FROM categories;
		
	8.Retrieve the details of the orders made by a specific customer.
	
		SELECT * 
		FROM orders 
		WHERE orderID = 10248;
	
	9.Show the oldest employee's name and birthdate from the "employees" table.
		
		SELECT firstname, birthdate 
		FROM Employees
		ORDER BY birthdate ASC LIMIT 1;

	10.Display the names of all products along with their prices.
	
		SELECT productname, price
		FROM Products;
	
** FILTERING AND SORTING **

	Retrieve orders placed in a specific country.
	List products with a price greater than $50.
	Show orders placed after a specific date.
	Display products from a specific category, sorted by price in descending order.
	Find customers whose names start with the letter 'A'.
	Show orders with more than 3 items (quantity).
	Retrieve customers who are from either the USA or Canada.
	List products with a price between $20 and $50.
	Display orders sorted by the order date in descending order.
	Find the three most recent orders.
	
** JOINS **

	Retrieve orders with customer details (customer name, contact, etc.).
	List all products with their category names.
	Display orders along with the employee names who processed them.
	Find suppliers with the products they supply.
	Show orders along with the shipper's name.
	List all products with their supplier details.
	Display the employee names along with their manager's name.
	Retrieve orders with product details.
	List customers who have not placed any orders.
	Show orders with customer details and the products they ordered.

** AGGREGATION **

	Find the total number of products in each category.
	Display the average quantity of products ordered.
	Find the customer who placed the most orders.
	Show the total sales for each product (quantity * price).
	Find the employee with the highest number of orders processed.
	Display the total revenue generated by each category.
	Find the customer who spent the most on orders.
	Show the number of orders placed by each customer.
	Display the average order value.
	Find the product with the highest price.

** SUBQUERIES **

	List customers who placed orders in a specific country.
	Find products with a price higher than the average price.
	Show customers who placed more than two orders.
	Display employees who were born after their managers.
	Find orders with a quantity greater than the average quantity.
	List customers who haven't placed any orders.
	Display products with a price higher than the maximum price in a specific category.
	Find orders placed on the same day as a specific order.
	Show products with a price lower than the minimum price in a specific category.
	Find orders placed by customers from a specific country.

** Advanced Queries **

	Display the cumulative sum of quantities ordered for each product.
	Find the nth highest salary from the "employees" table.
	Show the running total of revenue generated by each product.
	Display the top 5 customers who spent the most.
	Find the products with the highest and lowest prices in each category.
	List customers who placed orders in consecutive months.
	Show the orders with the longest time gap between them.
	Find the percentage of total revenue contributed by each product.
	Display the top 10% of customers who spent the most.
	List the products that were never ordered.
	
** MODIFYING DATA **

	Insert a new customer into the "customers" table.
	Update the price of a specific product.
	Delete a customer and all their orders.
	Insert a new category into the "categories" table.
	Update the quantity of a specific product in an order.
	Delete all orders placed before a specific date.
	Insert a new product along with its supplier and category details.
	Update the city of a specific supplier.
	Delete a product and update the related orders accordingly.
	Insert a new order along with customer, employee, and product details.
